worlds:
  # world name
  world:
    # variables preset: "x" "y" and "z", representing the entity's location
    # it is recommended to set common constant values outside the calculation
    centerX: '123'
    centerY: '62'
    centerZ: '-672'
    horizontalDistancePerLevel: '80'
    offset: '40'
    verticalDistancePerLevel: '10'
    distance: 'sqrt((x-centerX)^2+(z-centerZ)^2)'
    actualDistance: 'max(0,distance-offset)'
    levelHorizontal: 'min(100,floor(actualDistance/horizontalDistancePerLevel))'
    levelVertical: 'floor(max(0,centerY-y)/verticalDistancePerLevel)'
    # "level" is a special value: target of calculation
    level: 'levelHorizontal+levelVertical+1'
entities:
  ZOMBIE:
    Default:
      # variation probability is 'weight / sum of all weights of this entity type'
      weight: '1000'
      # show entities name over entity (like player names)
      name-visible: true
      # change the entities name, this has effect over the shown name (see name-visible) but also the death message
      name: '$variation-$type Level $level'
      attributes:
        GENERIC_MAX_HEALTH: '10+floor(level/10) * (1 + ((random > 0.8) * (random / 2)))'
      loot:
        rotten-flesh:
          type: ROTTEN_FLESH
          amount: '1 + randomInt(3)'
        zombie-feather:
          drop-chance: '(level > 30) * 0.01 + 0.01 * min(50, level)'
          type: FEATHER
