centers:
  my_world:
    x: 123
    y: 62
    z: -672
horizontal:
  level-per-meter: 0.0125
vertical:
  only-down: true # being higher as center-y doesn't increase level
  level-per-meter: 0.2
entities:
  ZOMBIE:
    default:
      name:
        show-name: true # show entities name e.g. zombie
        show-level: true # show generated level
        custom-name: 'Zombie' # override the entities default name
      loot:
        rotten-flesh:
          # rarity not set, item will drop every time
          type: ROTTEN_FLESH
          data: 0
          amount:
            min: 0
            add-min-per-level: 0.025 # min won't get bigger than max
            max: 2
            add-min-per-level: 0.02 # if min reaches max they won't swap
          # name not set, using Minecraft default
          # lore not set, setting no lore
        zombie-feather:
          since-level: 30 # starting level is 30, not 1
          rarity:
            base: 100 # probability is (1 / rarity)
            per-level: -2
            min: 50
          type: FEATHER # good old times
          data: 0
          amount:
            min: 1
            max: 1
          name: 'Zombies'' Feather'
          lore:
            - 'They love them!'
      health:
        base: 10
        per-level: 1 # add per-level*level to base, using operation
        # operation not set, using ADD_NUMBER
        # max not set, max is Integer.MAX_VALUE
      speed:
        # base not set, using Minecraft default
        per-level: 0.01 # may be omitted for setting base value for all values
        operation: ADD_SCALAR # possible values: ADD_NUMBER (default), ADD_SCALAR or MULTIPLY_SCALAR_1
        max: 1 # max of per-level*level
      damage:
        per-level: 0.01
        operation: ADD_SCALAR # possible values: ADD_NUMBER (default), ADD_SCALAR or MULTIPLY_SCALAR_1
        max: 1 # max of per-level*level
    boss:
      name:
        # custom-name not set, using name as defined for whole mob type
        show-level: false # this is a boss but can we defeat it?
        add-boss: true # add "Boss" before name to indicate special status
      rarity: 1000 # probability is (1 / rarity) 0 means disabled
      equip:
        bobs-sword:
          # equip-rarity not set, equip allways
          drop-rarity: 1 # always drop equipped item, default is 0, meaning never
          type: IRON_SWORD
          data: 5
          amount:
            min: 1
            max: 1
          name: 'Bob''s Magic Sword'
          lore:
            - 'He fought his whole live and'
            - 'after-live with this weapon.'
          enchantments:
            SHARPNESS: 1
            LOOTING: 2
      health:
        base: 100
        per-level: 10
      speed:
        base: 0.2 # bosses are slower than normal zombies
      damage:
        base: 16
        per-level: 0.25
        operation: ADD_SCALAR
        max: 35
