name: "${project.name}"
version: ${version}
main: ${basePackage}.${mainClass}

description: "${project.description}"
author: 'seyfahni'
website: "${project.url}"

commands:
  dynamicMonstersReloadConfig:
    description: 'Reloads the config'
    usage: /<command>
    permission: dmreload.command
    aliases: [dmreload, dmrelaodconfig]
